server {
  listen 80;
  server_name localhost;
  location / {
        proxy_pass http://localhost:3000;  # Change the port to your Node.js application's port
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

  # Cache static assets
  location ~* \.(jpg|jpeg|gif|png|ico|css|js|woff|woff2|svg|ttf|eot)$ {
    expires 7d;
    add_header Cache-Control "public";
  }

  location /sitemap.xml {
        alias /usr/share/nginx/html/sitemap.xml;
    }

  location /6acf3a56e2744262b140db296d0d8dcb.txt {
        alias /usr/share/nginx/html/6acf3a56e2744262b140db296d0d8dcb.txt;
  }

  location /robots.txt {
        alias /usr/share/nginx/html/robots.txt;
  }

  # Handle client-side routing
  location / {
    try_files $uri $uri/ /index.html;
  }
}