name: Sombatout Staging Environment
on:
  pull_request:
    types: [closed]
    paths:
        "sombatout/**"
  workflow_dispatch:
env:
    APP_MODE: website
    NUXT_APP_TITLE:  Sombatout
jobs:
  build-noocash-dev:
    defaults:
      run:
        working-directory: sombatout
    if: github.event.pull_request.merged==true
    name: build-noocash-dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GIT_TOKEN }}
    - name: Setup Environmental Variables
      run: |
        echo "
        VITE_FIREBASE_apiKey=${{secrets.VITE_FIREBASE_apiKey}}
        VITE_FIREBASE_authDomain=${{secrets.VITE_FIREBASE_authDomain}}
        VITE_FIREBASE_projectId=${{secrets.VITE_FIREBASE_projectId}}
        VITE_FIREBASE_storageBucket=${{secrets.VITE_FIREBASE_storageBucket}}
        VITE_FIREBASE_messagingSenderId=${{secrets.VITE_FIREBASE_messagingSenderId}}
        VITE_FIREBASE_appId=${{secrets.VITE_FIREBASE_appId}}
        VITE_FIREBASE_measurementId=${{secrets.VITE_FIREBASE_measurementId}}
        ">.env
    - name: Build and Push Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/sombatout:dev .
        docker push ghcr.io/${{ github.repository_owner }}/sombatout:dev
     
  deploy:
    runs-on: ubuntu-latest
    needs: build-noocash-dev
    name: deploy-noocash-dev
    steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Login to azure
            uses: azure/login@v1
            with:
              creds: ${{ secrets.SOMBATOUT_DEV_AZURE_CREDENTIALS }}
          - name: Deploy to Azure Web App
            uses: azure/webapps-deploy@v2
            with:
              app-name: ${{secrets.SOMBATOUT_DEV_APP_NAME}}
              images: 'ghcr.io/${{ github.repository_owner }}/sombatout:dev'
      